name: "Composer Tests centralised"

on:
    schedule:
      - cron: '0 3 * * 1,3,5'
    workflow_dispatch:
    push:
        paths-ignore:
          - 'doc/**'
          - '**.md'
        branches:
          - "[0-9]+.[0-9]+"
          - "[0-9]+.x"
    pull_request:
      paths-ignore:
        - 'doc/**'
        - '**.md'
      types: [ opened, synchronize, reopened ]

env:
  PIMCORE_PROJECT_ROOT: ${{ github.workspace }}

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
  test-composer:
    uses: pimcore/workflows-collection-public/.github/workflows/reusable-composer-test.yml@main
